server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: projetos
          uri: lb://PROJETO-SERVICE
          predicates:
            - Path=/project/**
        - id: services
          uri: lb://SERVICE-SERVICE
          predicates:
            - Path=/service/**
        - id: services_main
          uri: lb://SERVICE-SERVICE
          predicates:
            - Path=/main/**
        - id: comments
          uri: lb://COMMENTS
          predicates:
            - Path=/comentarios/**
        - id: comments_sections
          uri: lb://COMMENTS
          predicates:
            - Path=/secoes/**
        - id: aluno
          uri: lb://ALUNOSERVICE
          predicates:
            - Path=/aluno/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
  openapi-gateway:
    services:
      - name: PROJETO-SERVICE
        url: lb://PROJETO-SERVICE/project/v3/api-docs
      - name: SERVICE-SERVICE
        url: lb://SERVICE-SERVICE/service/v3/api-docs
      - name: COMMENTS
        url: lb://COMMENTS/comentarios/v3/api-docs
      - name: ALUNOSERVICE
        url: lb://ALUNOSERVICE/aluno/v3/api-docs


management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
